# Generated by Django 3.1.5 on 2021-02-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='club',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='squad',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='year_seven_year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='club',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
