# Generated by Django 3.1.5 on 2021-04-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance_data',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('4-', '4-'), ('2-', '2-'), ('4x', '4x'), ('4+', '4+'), ('2x', '2x'), ('1x', '1x'), ('4x+', '4x+'), ('8+', '8+')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='distance_data',
            name='type',
            field=models.CharField(blank=True, choices=[('strength', 'strength'), ('cross training', 'cross training'), ('rowing', 'rowing'), ('active recovery', 'active recovery'), ('swimming', 'swimming'), ('bike', 'bike'), ('erg', 'erg'), ('running', 'running')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('4-', '4-'), ('2-', '2-'), ('4x', '4x'), ('4+', '4+'), ('2x', '2x'), ('1x', '1x'), ('4x+', '4x+'), ('8+', '8+')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='type',
            field=models.CharField(blank=True, choices=[('strength', 'strength'), ('cross training', 'cross training'), ('rowing', 'rowing'), ('active recovery', 'active recovery'), ('swimming', 'swimming'), ('bike', 'bike'), ('erg', 'erg'), ('running', 'running')], max_length=256, null=True),
        ),
    ]
