# Generated by Django 3.1.5 on 2021-02-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0005_auto_20210216_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='boat_class',
            field=models.CharField(choices=[('4x', '4x'), ('8+', '8+'), ('4x+', '4x+'), ('4-', '4-'), ('2-', '2-'), ('1x', '1x'), ('4+', '4+'), ('2x', '2x')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='type',
            field=models.CharField(choices=[('strength', 'strength'), ('rowing', 'rowing'), ('erg', 'erg'), ('cycling', 'cycling'), ('active recovery', 'active recovery'), ('cross training', 'cross training'), ('running', 'running'), ('swimming', 'swimming')], max_length=256, null=True),
        ),
    ]
