# Generated by Django 3.1.5 on 2021-02-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0006_auto_20210216_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontEnd.club'),
        ),
        migrations.AlterField(
            model_name='result',
            name='boat_class',
            field=models.CharField(choices=[('4x+', '4x+'), ('2-', '2-'), ('4+', '4+'), ('2x', '2x'), ('8+', '8+'), ('4-', '4-'), ('4x', '4x'), ('1x', '1x')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='type',
            field=models.CharField(choices=[('running', 'running'), ('cross training', 'cross training'), ('swimming', 'swimming'), ('strength', 'strength'), ('active recovery', 'active recovery'), ('cycling', 'cycling'), ('erg', 'erg'), ('rowing', 'rowing')], max_length=256, null=True),
        ),
    ]
