# Generated by Django 3.1.5 on 2021-02-20 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontEnd', '0008_auto_20210218_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('4x+', '4x+'), ('2x', '2x'), ('1x', '1x'), ('4x', '4x'), ('2-', '2-'), ('8+', '8+'), ('4-', '4-'), ('4+', '4+')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='type',
            field=models.CharField(blank=True, choices=[('cross training', 'cross training'), ('rowing', 'rowing'), ('swimming', 'swimming'), ('active recovery', 'active recovery'), ('strength', 'strength'), ('bike', 'bike'), ('running', 'running'), ('erg', 'erg')], max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='Distance_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('boat_class', models.CharField(blank=True, choices=[('4x+', '4x+'), ('2x', '2x'), ('1x', '1x'), ('4x', '4x'), ('2-', '2-'), ('8+', '8+'), ('4-', '4-'), ('4+', '4+')], max_length=10, null=True)),
                ('distance', models.PositiveIntegerField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('rate', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(blank=True, choices=[('cross training', 'cross training'), ('rowing', 'rowing'), ('swimming', 'swimming'), ('active recovery', 'active recovery'), ('strength', 'strength'), ('bike', 'bike'), ('running', 'running'), ('erg', 'erg')], max_length=256, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.athlete')),
            ],
        ),
    ]
