# Generated by Django 3.1.5 on 2021-02-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0009_auto_20210220_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season_Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=256)),
                ('season', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='athlete',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='distance_data',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('4-', '4-'), ('8+', '8+'), ('1x', '1x'), ('4+', '4+'), ('2-', '2-'), ('4x+', '4x+'), ('2x', '2x'), ('4x', '4x')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='distance_data',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distance_data',
            name='type',
            field=models.CharField(blank=True, choices=[('bike', 'bike'), ('swimming', 'swimming'), ('strength', 'strength'), ('erg', 'erg'), ('running', 'running'), ('cross training', 'cross training'), ('rowing', 'rowing'), ('active recovery', 'active recovery')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('4-', '4-'), ('8+', '8+'), ('1x', '1x'), ('4+', '4+'), ('2-', '2-'), ('4x+', '4x+'), ('2x', '2x'), ('4x', '4x')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='type',
            field=models.CharField(blank=True, choices=[('bike', 'bike'), ('swimming', 'swimming'), ('strength', 'strength'), ('erg', 'erg'), ('running', 'running'), ('cross training', 'cross training'), ('rowing', 'rowing'), ('active recovery', 'active recovery')], max_length=256, null=True),
        ),
    ]
