# Generated by Django 3.1.5 on 2021-02-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0010_auto_20210222_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='distance_data',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('4x+', '4x+'), ('4+', '4+'), ('8+', '8+'), ('4-', '4-'), ('1x', '1x'), ('4x', '4x'), ('2-', '2-'), ('2x', '2x')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='distance_data',
            name='type',
            field=models.CharField(blank=True, choices=[('rowing', 'rowing'), ('active recovery', 'active recovery'), ('erg', 'erg'), ('strength', 'strength'), ('swimming', 'swimming'), ('bike', 'bike'), ('cross training', 'cross training'), ('running', 'running')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('4x+', '4x+'), ('4+', '4+'), ('8+', '8+'), ('4-', '4-'), ('1x', '1x'), ('4x', '4x'), ('2-', '2-'), ('2x', '2x')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='type',
            field=models.CharField(blank=True, choices=[('rowing', 'rowing'), ('active recovery', 'active recovery'), ('erg', 'erg'), ('strength', 'strength'), ('swimming', 'swimming'), ('bike', 'bike'), ('cross training', 'cross training'), ('running', 'running')], max_length=256, null=True),
        ),
    ]
