# Generated by Django 3.1.5 on 2021-02-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0011_auto_20210222_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance_data',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('2-', '2-'), ('4-', '4-'), ('4x', '4x'), ('4x+', '4x+'), ('2x', '2x'), ('4+', '4+'), ('1x', '1x'), ('8+', '8+')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='distance_data',
            name='type',
            field=models.CharField(blank=True, choices=[('erg', 'erg'), ('bike', 'bike'), ('rowing', 'rowing'), ('strength', 'strength'), ('swimming', 'swimming'), ('running', 'running'), ('cross training', 'cross training'), ('active recovery', 'active recovery')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('2-', '2-'), ('4-', '4-'), ('4x', '4x'), ('4x+', '4x+'), ('2x', '2x'), ('4+', '4+'), ('1x', '1x'), ('8+', '8+')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='type',
            field=models.CharField(blank=True, choices=[('erg', 'erg'), ('bike', 'bike'), ('rowing', 'rowing'), ('strength', 'strength'), ('swimming', 'swimming'), ('running', 'running'), ('cross training', 'cross training'), ('active recovery', 'active recovery')], max_length=256, null=True),
        ),
    ]
