# Generated by Django 3.1.5 on 2021-02-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0012_auto_20210222_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance_data',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('4+', '4+'), ('2-', '2-'), ('4x', '4x'), ('4x+', '4x+'), ('4-', '4-'), ('8+', '8+'), ('2x', '2x'), ('1x', '1x')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='distance_data',
            name='type',
            field=models.CharField(blank=True, choices=[('swimming', 'swimming'), ('erg', 'erg'), ('rowing', 'rowing'), ('strength', 'strength'), ('running', 'running'), ('active recovery', 'active recovery'), ('cross training', 'cross training'), ('bike', 'bike')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('4+', '4+'), ('2-', '2-'), ('4x', '4x'), ('4x+', '4x+'), ('4-', '4-'), ('8+', '8+'), ('2x', '2x'), ('1x', '1x')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='type',
            field=models.CharField(blank=True, choices=[('swimming', 'swimming'), ('erg', 'erg'), ('rowing', 'rowing'), ('strength', 'strength'), ('running', 'running'), ('active recovery', 'active recovery'), ('cross training', 'cross training'), ('bike', 'bike')], max_length=256, null=True),
        ),
    ]
