# Generated by Django 3.1.5 on 2021-02-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0013_auto_20210222_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='distance_data',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('4+', '4+'), ('4x', '4x'), ('1x', '1x'), ('2x', '2x'), ('8+', '8+'), ('2-', '2-'), ('4-', '4-'), ('4x+', '4x+')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='distance_data',
            name='type',
            field=models.CharField(blank=True, choices=[('swimming', 'swimming'), ('bike', 'bike'), ('running', 'running'), ('strength', 'strength'), ('rowing', 'rowing'), ('erg', 'erg'), ('cross training', 'cross training'), ('active recovery', 'active recovery')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('4+', '4+'), ('4x', '4x'), ('1x', '1x'), ('2x', '2x'), ('8+', '8+'), ('2-', '2-'), ('4-', '4-'), ('4x+', '4x+')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='type',
            field=models.CharField(blank=True, choices=[('swimming', 'swimming'), ('bike', 'bike'), ('running', 'running'), ('strength', 'strength'), ('rowing', 'rowing'), ('erg', 'erg'), ('cross training', 'cross training'), ('active recovery', 'active recovery')], max_length=256, null=True),
        ),
    ]
