# Generated by Django 3.1.5 on 2021-02-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0014_auto_20210222_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='distance_data',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('8+', '8+'), ('2-', '2-'), ('4x+', '4x+'), ('2x', '2x'), ('4x', '4x'), ('4-', '4-'), ('4+', '4+'), ('1x', '1x')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='distance_data',
            name='type',
            field=models.CharField(blank=True, choices=[('cross training', 'cross training'), ('active recovery', 'active recovery'), ('bike', 'bike'), ('swimming', 'swimming'), ('running', 'running'), ('rowing', 'rowing'), ('erg', 'erg'), ('strength', 'strength')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('8+', '8+'), ('2-', '2-'), ('4x+', '4x+'), ('2x', '2x'), ('4x', '4x'), ('4-', '4-'), ('4+', '4+'), ('1x', '1x')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='type',
            field=models.CharField(blank=True, choices=[('cross training', 'cross training'), ('active recovery', 'active recovery'), ('bike', 'bike'), ('swimming', 'swimming'), ('running', 'running'), ('rowing', 'rowing'), ('erg', 'erg'), ('strength', 'strength')], max_length=256, null=True),
        ),
    ]
