# Generated by Django 3.1.5 on 2021-03-12 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0016_auto_20210222_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance_data',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('2x', '2x'), ('8+', '8+'), ('4+', '4+'), ('2-', '2-'), ('4x+', '4x+'), ('1x', '1x'), ('4-', '4-'), ('4x', '4x')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='distance_data',
            name='type',
            field=models.CharField(blank=True, choices=[('erg', 'erg'), ('running', 'running'), ('strength', 'strength'), ('cross training', 'cross training'), ('bike', 'bike'), ('swimming', 'swimming'), ('rowing', 'rowing'), ('active recovery', 'active recovery')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='boat_class',
            field=models.CharField(blank=True, choices=[('2x', '2x'), ('8+', '8+'), ('4+', '4+'), ('2-', '2-'), ('4x+', '4x+'), ('1x', '1x'), ('4-', '4-'), ('4x', '4x')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='frontEnd.session_data'),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='type',
            field=models.CharField(blank=True, choices=[('erg', 'erg'), ('running', 'running'), ('strength', 'strength'), ('cross training', 'cross training'), ('bike', 'bike'), ('swimming', 'swimming'), ('rowing', 'rowing'), ('active recovery', 'active recovery')], max_length=256, null=True),
        ),
    ]
